export const productsData = [
    {
        id: 1,
        sku: 18644119330491312,
        title: "Licensed Metal",
        quantity: 1,
        description: "Licensed Metal Bike",
        availableSizes: ["X", "L", "XL", "XXL"],
        price: 543.00,
        isFreeShipping: true,
    },
    {
        id: 2,
        sku: 18644119430491312,
        title: "Awesome Plastic",
        quantity: 1,
        description: "Awesome Plastic Shirt",
        availableSizes: ["X", "L", "XL", "XXL"],
        price: 543.00,
        isFreeShipping: true,
    },
    {
        id: 3,
        sku: 18644219330491312,
        title: "Handcrafted Concrete",
        quantity: 1,
        description: "Handcrafted Concrete Computer",
        availableSizes: ["X", "L", "M"],
        price: 123,
        isFreeShipping: true,
    },
    {
        id: 4,
        sku: 18644119330481312,
        title: "Tasty Frozen",
        quantity: 1,
        description: "Tasty Frozen Compute",
        availableSizes: ["XL", "XS"],
        price: 29.00,
        isFreeShipping: true,
    },
    {
        id: 5,
        sku: 18644119330471312,
        title: "Incredible Concrete",
        quantity: 1,
        description: "Incredible Concrete Cheese",
        availableSizes: ["X", "L", "XL", "Xs"],
        price: 99,
        isFreeShipping: true,
    },
    {
        id: 6,
        sku: 18644119330461312,
        title: "Incredible Granite",
        quantity: 1,
        description: "Incredible Granite Ball",
        availableSizes: ["X", "XS"],
        price: 256,
        isFreeShipping: true,
    },
    {
        id: 7,
        sku: 18644119330451312,
        title: "Gorgeous Granite",
        quantity: 1,
        description: "Gorgeous Granite Table",
        availableSizes: ["X", "L", "XL", "XXL"],
        price: 10,
        isFreeShipping: true,
    },
  ]